GET http://localhost:3000/places?text=guaratuba, pr

## Create a route
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "rota teste",
  "source_id": "11111", 
  "destination_id": "11111"
}

###
GET http://localhost:3000/places?text=manaus, am

###
GET http://localhost:3000/directions?originId=ChIJt0d2s8gbbJIRzKll959cSCs&destinationId=OyKP625QRcyrMGqegO1I

